Vagrant::Config.run do |config|
  @application = "my_app"
  
  config.vm.box = "lucid32"
  config.vm.customize do |vm|
    vm.name = @application
    vm.memory_size = 512
  end

  config.vm.network("33.33.33.10")
  # config.vm.forward_port("http", 80, 4282)
  config.vm.share_folder("v-root", "/srv/#{@application}/current", ".", :nfs => true)
  # config.vm.boot_mode = :gui
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "deploy/cookbooks"
    
    chef.run_list = %w(
      recipe[apt]
      recipe[server]
      recipe[ruby192]
      recipe[logrotate]
      recipe[unicorn]
      recipe[nginx]
      recipe[redis]
      recipe[site]
    )
  
    chef.json.merge!({
      :app => {
        :uri         => "#{@application}.local",
        :application => "#{@application}",
        :environment => "development",
        :user        => "vagrant",
        :rails       => false
      }
    })
    
    chef.log_level = :debug
  end
end
